[package]
name = "desk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
btleplug = "*"
futures = "*"
once_cell = "*"
slog = "*"
slog-term = "*"
structopt = "*"
strum = {version="*", features=["derive"]}
tokio = {version="*", features=["macros"]}
uuid = "*"
