[package]
name = "desklink-common"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "*"
prost = "*"
serde = "*"
slog = "*"
thiserror = "*"
tonic = "*"

[build-dependencies]
tonic-build = "*"
